import {notFound} from "next/navigation";
import {auth} from "@/auth";
import {connectDB} from "@/lib/db";
import Order from "@/models/Order";
import Shipment from "@/models/Shipment";
import Refund from "@/models/Refund";
import ReturnRequest from "@/models/Return";
import StatusBadge from "@/components/ui/StatusBadge";
import OrderActions from "@/components/account/OrderActions";
export default async function Page({params}){const s=await auth();const{id}=await params;await connectDB();const[order,shipment,refunds,returns]=await Promise.all([Order.findOne({_id:id,user:s.user.id}).lean(),Shipment.findOne({order:id}).lean(),Refund.find({order:id,user:s.user.id}).sort({createdAt:-1}).lean(),ReturnRequest.find({order:id,user:s.user.id}).sort({createdAt:-1}).lean()]);if(!order)notFound();return <><div className="dashboard-head"><div><span className="eyebrow">{order.orderNumber}</span><h1>Order detail.</h1></div><StatusBadge value={order.status}/></div><div className="form-card"><h2>Timeline</h2>{order.timeline.map((e,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"150px 1fr",gap:14,padding:"10px 0",borderBottom:"1px solid #eee"}}><span className="muted">{new Date(e.at).toLocaleString()}</span><div><StatusBadge value={e.status}/><p style={{margin:"6px 0 0"}}>{e.note}</p></div></div>)}</div>{shipment&&<div className="form-card"><h2>Shipment</h2><p><strong>{shipment.provider}</strong> · {shipment.trackingNumber}</p>{shipment.trackingUrl&&<a className="button small" href={shipment.trackingUrl} target="_blank" rel="noreferrer">Carrier tracking</a>}<p className="muted">Estimated delivery: {shipment.estimatedDelivery?new Date(shipment.estimatedDelivery).toLocaleDateString():"Pending"}</p>{shipment.events?.map((e,i)=><div className="summary-line" key={i}><span>{new Date(e.at).toLocaleString()} · {e.status}</span><span>{e.location||e.message}</span></div>)}</div>}<div className="form-card"><h2>Items</h2>{order.items.map((i,idx)=><div className="summary-line" key={idx}><span>{i.name} × {i.quantity}</span><strong>{order.currency} {i.subtotal.toFixed(2)}</strong></div>)}<div className="summary-line total"><span>Total</span><span>{order.currency} {order.total.toFixed(2)}</span></div></div>{refunds.length>0&&<div className="form-card"><h2>Refunds</h2>{refunds.map(r=><div className="summary-line" key={String(r._id)}><span>{r.reason}<br/><small className="muted">{r.destination}</small></span><span><StatusBadge value={r.status}/> · {order.currency} {r.amount.toFixed(2)}</span></div>)}</div>}{returns.length>0&&<div className="form-card"><h2>Returns</h2>{returns.map(r=><div className="summary-line" key={String(r._id)}><span>{r.items.length} item(s) · {r.resolution}</span><StatusBadge value={r.status}/></div>)}</div>}<OrderActions order={JSON.parse(JSON.stringify(order))}/></>}
