import { auth } from "@/auth";
import { connectDB } from "@/lib/db";
import ChatConversation from "@/models/ChatConversation";
import ChatMessage from "@/models/ChatMessage";
import User from "@/models/User";
import { messageSchema } from "@/lib/validation/commerce";
import { rateLimit, requestKey } from "@/lib/security/rate-limit";
import { fail, fromError, ok, readJson } from "@/lib/api";
export async function GET(request,{params}){try{const session=await auth();if(!session?.user?.id)return fail("Authentication required",401);const{id}=await params;await connectDB();const conversation=await ChatConversation.findOne({_id:id,user:session.user.id}).populate("assignedAgent","name avatar lastSeenAt");if(!conversation)return fail("Conversation not found",404);const since=new URL(request.url).searchParams.get("since");const filter={conversation:id};if(since)filter.createdAt={$gt:new Date(since)};const items=await ChatMessage.find(filter).populate("sender","name avatar").sort({createdAt:1}).limit(200).lean();conversation.userLastReadAt=new Date();conversation.userTypingUntil=null;await conversation.save();await User.updateOne({_id:session.user.id},{$set:{lastSeenAt:new Date()}});const online=conversation.assignedAgent?.lastSeenAt&&Date.now()-new Date(conversation.assignedAgent.lastSeenAt).getTime()<90000;return ok({items,pollAfterMs:4000,presence:{agentOnline:Boolean(online),agentTyping:Boolean(conversation.agentTypingUntil&&conversation.agentTypingUntil>new Date()),agentName:conversation.assignedAgent?.name||"Support"},readAt:conversation.agentLastReadAt})}catch(error){return fromError(error,"Unable to load messages")}}
export async function POST(request,{params}){try{const session=await auth();if(!session?.user?.id)return fail("Authentication required",401);if(!(await rateLimit(requestKey(request,"support-message"),{limit:60,windowSeconds:60})))return fail("Message rate limit exceeded",429);const{id}=await params;const parsed=messageSchema.safeParse(await readJson(request));if(!parsed.success)return fail("Invalid message",400,parsed.error.flatten().fieldErrors);await connectDB();const conversation=await ChatConversation.findOne({_id:id,user:session.user.id});if(!conversation)return fail("Conversation not found",404);const message=await ChatMessage.create({conversation:id,sender:session.user.id,senderRole:"customer",body:parsed.data.body,attachments:parsed.data.attachments});conversation.lastMessageAt=new Date();conversation.userTypingUntil=null;conversation.status=conversation.status==="closed"?"open":conversation.status;await conversation.save();await User.updateOne({_id:session.user.id},{$set:{lastSeenAt:new Date()}});return ok({message},{status:201})}catch(error){return fromError(error,"Unable to send message")}}
export async function PATCH(request,{params}){try{const session=await auth();if(!session?.user?.id)return fail("Authentication required",401);const{id}=await params;const{typing}=await readJson(request);await connectDB();const until=typing?new Date(Date.now()+7000):null;const result=await ChatConversation.updateOne({_id:id,user:session.user.id},{$set:{userTypingUntil:until}});if(!result.matchedCount)return fail("Conversation not found",404);await User.updateOne({_id:session.user.id},{$set:{lastSeenAt:new Date()}});return ok({updated:true})}catch(error){return fromError(error,"Unable to update typing state")}}
