import { auth } from "@/auth";
import { requirePermission, PERMISSIONS } from "@/lib/auth/permissions";
import { connectDB } from "@/lib/db";
import Category from "@/models/Category";
import { audit } from "@/lib/auth/audit";
import { fail, fromError, ok, readJson } from "@/lib/api";
export async function GET() { try { const session = await auth(); requirePermission(session, PERMISSIONS.PRODUCTS_READ); await connectDB(); return ok({ items: await Category.find({}).populate("parent", "name slug").sort({ sortOrder: 1, name: 1 }).lean() }); } catch (error) { return fromError(error, "Unable to load categories"); } }
export async function POST(request) { try { const session = await auth(); requirePermission(session, PERMISSIONS.CATEGORIES_WRITE); const body = await readJson(request); if (!body.name || !body.slug) return fail("Name and slug are required", 400); await connectDB(); const category = await Category.create(body); await audit({ actor: session.user.id, action: "category.created", resourceType: "Category", resourceId: category._id, newValue: body }); return ok({ category }, { status: 201 }); } catch (error) { return fromError(error, "Unable to create category"); } }
export async function PATCH(request) { try { const session = await auth(); requirePermission(session, PERMISSIONS.CATEGORIES_WRITE); const body = await readJson(request); await connectDB(); const previous = await Category.findById(body.id).lean(); if (!previous) return fail("Category not found", 404); const allowed = ["name","slug","parent","description","banner","featured","trending","sortOrder","filters","seo"]; const updates = Object.fromEntries(allowed.filter((key) => Object.prototype.hasOwnProperty.call(body, key)).map((key) => [key, body[key]])); const category = await Category.findByIdAndUpdate(id, { $set: updates }, { new: true, runValidators: true }); await audit({ actor: session.user.id, action: "category.updated", resourceType: "Category", resourceId: id, previousValue: previous, newValue: updates }); return ok({ category }); } catch (error) { return fromError(error, "Unable to update category"); } }
export async function DELETE(request) { try { const session = await auth(); requirePermission(session, PERMISSIONS.CATEGORIES_WRITE); const id = new URL(request.url).searchParams.get("id"); await connectDB(); if (await Category.exists({ parent: id })) return fail("Move or remove child categories first", 409); const previous = await Category.findByIdAndDelete(id).lean(); await audit({ actor: session.user.id, action: "category.deleted", resourceType: "Category", resourceId: id, previousValue: previous }); return ok({ deleted: true }); } catch (error) { return fromError(error, "Unable to delete category"); } }
