import { auth } from "@/auth";
import { connectDB } from "@/lib/db";
import Order from "@/models/Order";
import ReturnRequest from "@/models/Return";
import { notifyUser } from "@/lib/notifications";
import { emailTemplates } from "@/lib/email";
import { audit } from "@/lib/auth/audit";
import { fail, fromError, ok, readJson } from "@/lib/api";
export async function POST(request,{params}){try{const session=await auth();if(!session?.user?.id)return fail("Authentication required",401);const{id}=await params;const body=await readJson(request);await connectDB();const order=await Order.findOne({_id:id,user:session.user.id});if(!order)return fail("Order not found",404);if(order.status!=="delivered")return fail("Returns can be requested after delivery",409);const existing=await ReturnRequest.findOne({order:order._id,status:{$in:["requested","approved","received"]}});if(existing)return fail("A return request is already open",409);const itemMap=new Map(order.items.map((i)=>[`${i.product}:${i.variant||""}`,i]));const items=(body.items||[]).map((i)=>{const original=itemMap.get(`${i.product}:${i.variant||""}`);if(!original||i.quantity<1||i.quantity>original.quantity)throw Object.assign(new Error("Invalid return quantity"),{status:400});return{product:i.product,variant:i.variant||null,quantity:i.quantity,reason:String(i.reason||"").slice(0,1000)}});if(!items.length)return fail("Select at least one item",400);const result=await ReturnRequest.create({order:order._id,user:session.user.id,items});order.timeline.push({status:order.status,note:"Return request submitted",actor:session.user.id});await order.save();await audit({actor:session.user.id,action:"return.requested",resourceType:"Return",resourceId:result._id,newValue:{order:order.orderNumber,items:items.length}});await notifyUser(session.user.id,{type:"return_requested",title:`Return requested for ${order.orderNumber}`,message:"Your return request was received and is awaiting review.",href:`/account/orders/${order._id}`,email:emailTemplates.returnStatus(order.orderNumber,"requested")});return ok({returnRequest:result},{status:201})}catch(error){return fromError(error,"Unable to create return request")}}
