import { auth } from "@/auth";
import { requirePermission, PERMISSIONS } from "@/lib/auth/permissions";
import { connectDB } from "@/lib/db";
import Role from "@/models/Role";
import Permission from "@/models/Permission";
import { audit } from "@/lib/auth/audit";
import { fail, fromError, ok, readJson } from "@/lib/api";
export async function GET() { try { const session = await auth(); requirePermission(session, PERMISSIONS.ROLES_MANAGE); await connectDB(); const [roles, permissions] = await Promise.all([Role.find({}).populate("permissions").sort({ name: 1 }).lean(), Permission.find({}).sort({ key: 1 }).lean()]); return ok({ roles, permissions }); } catch (error) { return fromError(error, "Unable to load roles"); } }
export async function POST(request) { try { const session = await auth(); requirePermission(session, PERMISSIONS.ROLES_MANAGE); const body = await readJson(request); if (!body.name || !body.slug) return fail("Name and slug are required", 400); await connectDB(); const permissions = await Permission.find({ key: { $in: body.permissions || [] } }).select("_id"); const role = await Role.create({ name: body.name, slug: body.slug, permissions: permissions.map((p) => p._id), isSystem: false }); await audit({ actor: session.user.id, action: "role.created", resourceType: "Role", resourceId: role._id, newValue: body }); return ok({ role }, { status: 201 }); } catch (error) { return fromError(error, "Unable to create role"); } }
export async function PATCH(request) { try { const session = await auth(); requirePermission(session, PERMISSIONS.ROLES_MANAGE); const body = await readJson(request); await connectDB(); const role = await Role.findById(body.id); if (!role) return fail("Role not found", 404); const previous = role.toObject(); if (body.name) role.name = body.name; if (Array.isArray(body.permissions)) { const permissions = await Permission.find({ key: { $in: body.permissions } }).select("_id"); role.permissions = permissions.map((p) => p._id); } await role.save(); await audit({ actor: session.user.id, action: "role.updated", resourceType: "Role", resourceId: role._id, previousValue: previous, newValue: body }); return ok({ role }); } catch (error) { return fromError(error, "Unable to update role"); } }
