import { auth } from "@/auth";
import { requirePermission, PERMISSIONS } from "@/lib/auth/permissions";
import { connectDB } from "@/lib/db";
import Product from "@/models/Product";
import ProductVariant from "@/models/ProductVariant";
import { audit } from "@/lib/auth/audit";
import { fail, fromError, ok, readJson } from "@/lib/api";
export async function GET(_request, { params }) { try { const session = await auth(); requirePermission(session, PERMISSIONS.PRODUCTS_READ); const { id } = await params; await connectDB(); const product = await Product.findById(id).lean(); if (!product) return fail("Product not found", 404); const variants = await ProductVariant.find({ product: id }).lean(); return ok({ product, variants }); } catch (error) { return fromError(error, "Unable to load product"); } }
export async function PATCH(request, { params }) { try { const session = await auth(); requirePermission(session, PERMISSIONS.PRODUCTS_WRITE); const { id } = await params; const body = await readJson(request); await connectDB(); const previous = await Product.findById(id).lean(); if (!previous) return fail("Product not found", 404); const { variants } = body;
    const allowed = ["name","slug","sku","shortDescription","description","categories","brand","tags","media","specifications","attributes","basePrice","compareAtPrice","costPrice","currency","stock","lowStockThreshold","trackInventory","allowBackorder","status","featured","trending","shipping","shippingInfo","returnInfo","seo","relatedProducts"];
    const updates = Object.fromEntries(allowed.filter((key) => Object.prototype.hasOwnProperty.call(body, key)).map((key) => [key, body[key]]));
    const product = await Product.findByIdAndUpdate(id, { $set: updates }, { new: true, runValidators: true }); if (Array.isArray(variants)) { await ProductVariant.deleteMany({ product: id }); if (variants.length) await ProductVariant.insertMany(variants.map((v) => ({ ...v, product: id }))); } await audit({ actor: session.user.id, action: "product.updated", resourceType: "Product", resourceId: id, previousValue: previous, newValue: updates }); return ok({ product }); } catch (error) { return fromError(error, "Unable to update product"); } }
export async function DELETE(_request, { params }) { try { const session = await auth(); requirePermission(session, PERMISSIONS.PRODUCTS_WRITE); const { id } = await params; await connectDB(); const previous = await Product.findById(id).lean(); if (!previous) return fail("Product not found", 404); await Promise.all([Product.deleteOne({ _id: id }), ProductVariant.deleteMany({ product: id })]); await audit({ actor: session.user.id, action: "product.deleted", resourceType: "Product", resourceId: id, previousValue: previous }); return ok({ deleted: true }); } catch (error) { return fromError(error, "Unable to delete product"); } }
