import { auth } from "@/auth";
import { requirePermission, PERMISSIONS } from "@/lib/auth/permissions";
import { connectDB } from "@/lib/db";
import ChatConversation from "@/models/ChatConversation";
import ChatMessage from "@/models/ChatMessage";
import User from "@/models/User";
import { messageSchema } from "@/lib/validation/commerce";
import { fail, fromError, ok, readJson } from "@/lib/api";
export async function GET(request, { params }) { try { const session = await auth(); requirePermission(session, PERMISSIONS.SUPPORT_MANAGE); const { id } = await params; await connectDB(); const conversation = await ChatConversation.findById(id).populate("user", "name avatar lastSeenAt"); if (!conversation) return fail("Conversation not found", 404); const since = new URL(request.url).searchParams.get("since"); const filter = { conversation: id }; if (since) filter.createdAt = { $gt: new Date(since) }; const items = await ChatMessage.find(filter).populate("sender", "name avatar").sort({ createdAt: 1 }).limit(300).lean(); conversation.agentLastReadAt = new Date(); conversation.agentTypingUntil = null; await conversation.save(); await User.updateOne({ _id: session.user.id }, { $set: { lastSeenAt: new Date() } }); const online = conversation.user?.lastSeenAt && Date.now() - new Date(conversation.user.lastSeenAt).getTime() < 90000; return ok({ items, pollAfterMs: 3500, presence: { customerOnline: Boolean(online), customerTyping: Boolean(conversation.userTypingUntil && conversation.userTypingUntil > new Date()) }, readAt: conversation.userLastReadAt }); } catch (error) { return fromError(error, "Unable to load messages"); } }
export async function POST(request, { params }) { try { const session = await auth(); requirePermission(session, PERMISSIONS.SUPPORT_MANAGE); const { id } = await params; const parsed = messageSchema.safeParse(await readJson(request)); if (!parsed.success) return fail("Invalid message", 400); await connectDB(); const conversation = await ChatConversation.findById(id); if (!conversation) return fail("Conversation not found", 404); const message = await ChatMessage.create({ conversation: id, sender: session.user.id, senderRole: "agent", body: parsed.data.body, attachments: parsed.data.attachments }); conversation.assignedAgent = conversation.assignedAgent || session.user.id; conversation.lastMessageAt = new Date(); conversation.agentTypingUntil = null; await conversation.save(); await User.updateOne({ _id: session.user.id }, { $set: { lastSeenAt: new Date() } }); return ok({ message }, { status: 201 }); } catch (error) { return fromError(error, "Unable to send message"); } }
export async function PATCH(request, { params }) { try { const session = await auth(); requirePermission(session, PERMISSIONS.SUPPORT_MANAGE); const { id } = await params; const { typing } = await readJson(request); await connectDB(); const result = await ChatConversation.updateOne({ _id: id }, { $set: { agentTypingUntil: typing ? new Date(Date.now() + 7000) : null, assignedAgent: session.user.id } }); if (!result.matchedCount) return fail("Conversation not found", 404); await User.updateOne({ _id: session.user.id }, { $set: { lastSeenAt: new Date() } }); return ok({ updated: true }); } catch (error) { return fromError(error, "Unable to update typing state"); } }
