"use client";
import { MuiButton } from "@/components/ui/MuiFormControls";
import { useMemo, useState } from "react";
import AddToCartButton from "@/components/storefront/AddToCartButton";
import WishlistButton from "@/components/storefront/WishlistButton";
import CompareButton from "@/components/storefront/CompareButton";
export default function ProductPurchase({ product }) {
  const [variantId,setVariantId]=useState(product.variants?.[0]?._id||null); const [qty,setQty]=useState(1); const variant=useMemo(()=>product.variants?.find(v=>String(v._id)===String(variantId)),[product.variants,variantId]); const price=variant?.price??product.basePrice; const compare=variant?.compareAtPrice??product.compareAtPrice; const stock=variant?.stock??product.stock;
  return <div><div className="product-price"><span>{product.currency||"USD"} {Number(price).toFixed(2)}</span>{compare>price&&<span className="price-old">{product.currency||"USD"} {Number(compare).toFixed(2)}</span>}</div><div className="rating-row" style={{marginTop:12}}>★ {Number(product.ratingAverage||0).toFixed(1)} · {product.ratingCount||0} reviews · <strong>{stock>0?`${stock} in stock`:product.allowBackorder?"Backorder available":"Out of stock"}</strong></div>{product.variants?.length>0&&<div className="option-group"><strong>Choose option</strong><div className="option-buttons" style={{marginTop:10}}>{product.variants.map(v=><MuiButton key={String(v._id)} className={`option-button ${String(variantId)===String(v._id)?"selected":""}`} onClick={()=>setVariantId(v._id)} disabled={!v.active}>{v.name}</MuiButton>)}</div></div>}<div className="buy-row"><div className="qty"><MuiButton onClick={()=>setQty(q=>Math.max(1,q-1))}>−</MuiButton><strong>{qty}</strong><MuiButton onClick={()=>setQty(q=>Math.min(99,q+1))}>+</MuiButton></div><AddToCartButton productId={String(product._id)} variantId={variantId?String(variantId):null} quantity={qty}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:8}}><AddToCartButton productId={String(product._id)} variantId={variantId?String(variantId):null} quantity={qty} buyNow className="button acid"/><WishlistButton productId={String(product._id)}/></div><div style={{marginTop:8}}><CompareButton slug={product.slug}/></div></div>;
}
