"use client";
import { MuiButton, MuiInput, MuiSelect, MuiTextarea } from "@/components/ui/MuiFormControls";
import { useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import { useToast } from "@/components/providers/ToastProvider";
export default function Reviews({ productId, productSlug, ratingAverage=0, ratingCount=0 }) {
  const {data:session}=useSession(); const {toast}=useToast();
  const [items,setItems]=useState([]); const [distribution,setDistribution]=useState({}); const [media,setMedia]=useState([]); const [uploading,setUploading]=useState(false);
  const [form,setForm]=useState({rating:5,title:"",body:""});
  const load=()=>fetch(`/api/reviews?productId=${productId}`).then(r=>r.json()).then(d=>{setItems(d.items||[]);setDistribution(d.distribution||{})}).catch(()=>{});
  useEffect(()=>{load()},[productId]);
  async function upload(files){if(!files?.length)return;if(!session){location.href=`/login?callbackUrl=/product/${productSlug}`;return;}setUploading(true);try{const r=await fetch('/api/reviews/upload-signature',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Upload unavailable');const uploaded=[];for(const file of [...files].slice(0,6-media.length)){const fd=new FormData();fd.set('file',file);fd.set('api_key',d.apiKey);fd.set('timestamp',String(d.timestamp));fd.set('signature',d.signature);fd.set('folder',d.folder);const u=await fetch(`https://api.cloudinary.com/v1_1/${d.cloudName}/auto/upload`,{method:'POST',body:fd});const x=await u.json();if(!u.ok)throw new Error(x.error?.message||'Upload failed');uploaded.push({type:x.resource_type==='video'?'video':'image',url:x.secure_url})}setMedia(v=>[...v,...uploaded].slice(0,6))}catch(e){toast(e.message,'error')}finally{setUploading(false)}}
  async function submit(e){e.preventDefault();if(!session){location.href=`/login?callbackUrl=/product/${productSlug}`;return;}const r=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId,...form,media})});const d=await r.json();toast(r.ok?'Review submitted for moderation':d.error||'Unable to submit',r.ok?'success':'error');if(r.ok){setForm({rating:5,title:'',body:''});setMedia([])}}
  async function vote(id,value){if(!session){location.href=`/login?callbackUrl=/product/${productSlug}`;return;}const r=await fetch(`/api/reviews/${id}/vote`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({value})});if(r.ok)load();else toast((await r.json()).error||'Unable to vote','error')}
  async function report(id){if(!session){location.href=`/login?callbackUrl=/product/${productSlug}`;return;}const reason=prompt('Why are you reporting this review?');if(!reason)return;const r=await fetch(`/api/reviews/${id}/report`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});toast(r.ok?'Review reported':'Unable to report review',r.ok?'success':'error')}
  return <section className="reviews-section"><div className="container"><div className="section-head"><div><span className="eyebrow">Customer reviews</span><h2 className="section-title">{Number(ratingAverage).toFixed(1)} / 5</h2><p>{ratingCount} ratings</p></div><div>{[5,4,3,2,1].map(n=><div key={n} style={{display:'flex',gap:8,fontSize:13}}><span>{n}★</span><span className="muted">{distribution[n]||0}</span></div>)}</div></div><div style={{display:'grid',gridTemplateColumns:'minmax(0,1.2fr) minmax(280px,.8fr)',gap:30}}><div>{items.length?items.map(r=><article key={r._id} className="data-card" style={{padding:20,marginTop:0,marginBottom:12}}><div>★ {r.rating} {r.verifiedPurchase&&<span className="status-badge status-approved">Verified purchase</span>}</div><h3>{r.title||'Customer review'}</h3><p className="muted" style={{lineHeight:1.65}}>{r.body}</p>{r.media?.length>0&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{r.media.map((m,i)=>m.type==='video'?<video key={i} src={m.url} controls style={{width:120,height:120,objectFit:'cover',borderRadius:10}}/>:<img key={i} src={m.url} alt="Review media" style={{width:120,height:120,objectFit:'cover',borderRadius:10}}/>)}</div>}<small>{r.user?.name||'Customer'}</small><div style={{display:'flex',gap:10,marginTop:12}}><MuiButton className="link-button" onClick={()=>vote(r._id,'helpful')}>Helpful ({r.helpfulCount||0})</MuiButton><MuiButton className="link-button" onClick={()=>vote(r._id,'unhelpful')}>Not helpful ({r.unhelpfulCount||0})</MuiButton><MuiButton className="link-button" onClick={()=>report(r._id)}>Report</MuiButton></div></article>):<p className="muted">No approved reviews yet.</p>}</div><form className="form-card" onSubmit={submit}><h2>Write a review</h2><div className="field"><label>Rating</label><MuiSelect value={form.rating} onChange={e=>setForm(f=>({...f,rating:Number(e.target.value)}))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} stars</option>)}</MuiSelect></div><div className="field"><label>Title</label><MuiInput value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></div><div className="field"><label>Review</label><MuiTextarea value={form.body} onChange={e=>setForm(f=>({...f,body:e.target.value}))} required/></div><div className="field"><label>Images/videos (up to 6)</label><MuiInput type="file" accept="image/*,video/*" multiple onChange={e=>upload(e.target.files)} disabled={uploading}/></div>{media.length>0&&<p className="muted">{media.length} media file(s) ready.</p>}<MuiButton className="button dark" disabled={uploading}>{uploading?'Uploading…':'Submit review'}</MuiButton></form></div></div></section>;
}
